project_id = "dpvdavjwqyviredzoorj"

[functions]
  [functions.ai-support-chat]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-product-content]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-order-email]
    verify_jwt = false
  [functions.ai-free-tools]
    verify_jwt = false
  [functions.generate-product-card]
    verify_jwt = false
  [functions.sitemap]
    verify_jwt = false
  [functions.notify-new-order]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.telegram-poll]
    verify_jwt = false
  [functions.telegram-poll-admin]
    verify_jwt = false
  [functions.prerender]
    verify_jwt = false
